version: '3'
 
services:
  db:
    image: mysql
    container_name: mysqldb
    env_file: 
    - ./app.env
    volumes:
    - ./docker/db/data:/var/lib/mysql
    ports:
    - 3306:3306
 
  app:
    build: '.'
    container_name: expressapp
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    tty: true
    env_file: 
      - ./app.env
    ports:
      - '3000:3000'
    command: npm start
